version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: quarkususer
      POSTGRES_PASSWORD: ultraverysecret
      POSTGRES_DB: uaicores_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
